# Generated by Django 5.0.6 on 2026-08-02 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_auth_version_user_email_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_team_invitations', models.BooleanField(default=True)),
                ('notify_join_requests', models.BooleanField(default=True)),
                ('notify_team_challenges', models.BooleanField(default=True)),
                ('notify_game_updates', models.BooleanField(default=True)),
                ('notify_booking_updates', models.BooleanField(default=True)),
                ('notify_cancellation_refunds', models.BooleanField(default=True)),
                ('notify_rating_reminders', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('public_profile_visible', models.BooleanField(default=True)),
                ('location_visible', models.BooleanField(default=True)),
                ('reliability_visible', models.BooleanField(default=True)),
                ('rating_visible', models.BooleanField(default=True)),
                ('allow_team_invitations', models.BooleanField(default=True)),
                ('allow_team_challenges', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
