# Generated by Django 5.0.6 on 2026-08-02 09:01

from django.db import migrations, models

def backfill_otp_email(apps, schema_editor):
    EmailVerificationOTP = apps.get_model("accounts", "EmailVerificationOTP")
    for otp in EmailVerificationOTP.objects.select_related("user").filter(email=""):
        otp.email = otp.user.email
        otp.save(update_fields=["email"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accountsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationotp',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='pending_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pending_email_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_otp_email, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='emailverificationotp',
            index=models.Index(fields=['email', '-created_at'], name='account_otp_email_created_idx'),
        ),
    ]
