# Generated by Django 5.2.16 on 2026-08-31 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_emailverificationotp_email_user_pending_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsettings',
            name='notify_chat_messages',
            field=models.BooleanField(default=True),
        ),
    ]
