# Generated by Django 5.2.16 on 2026-08-27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("teams", "0004_team_accepts_team_challenges"),
        ("venues", "0015_booking_matchmaking_sync_error_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamChallenge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("challenge_type", models.CharField(choices=[("DIRECT", "Direct challenge"), ("OPEN", "Open challenge")], default="DIRECT", max_length=12)),
                ("court_mode", models.CharField(choices=[("PLAN_FIRST", "Plan first"), ("BOOKING_FIRST", "Confirmed booking")], default="PLAN_FIRST", max_length=20)),
                ("team_pair_key", models.CharField(blank=True, max_length=40)),
                ("status", models.CharField(choices=[("OPEN", "Awaiting response"), ("COUNTERED", "Counter-proposal received"), ("ACCEPTED_AWAITING_BOOKING", "Court booking required"), ("RECONFIRMATION_REQUIRED", "Schedule change requested"), ("CONFIRMED", "Match confirmed"), ("DECLINED", "Declined"), ("WITHDRAWN", "Withdrawn"), ("EXPIRED", "Expired"), ("CANCELLED", "Cancelled"), ("COMPLETED", "Completed")], default="OPEN", max_length=35)),
                ("response_deadline", models.DateTimeField()),
                ("booking_deadline", models.DateTimeField(blank=True, null=True)),
                ("is_public", models.BooleanField(default=False)),
                ("client_request_id", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("booking", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="team_challenges", to="venues.booking")),
                ("booking_owner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="team_challenge_bookings", to=settings.AUTH_USER_MODEL)),
                ("challenged_team", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="received_team_challenges", to="teams.team")),
                ("challenger_team", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="sent_team_challenges", to="teams.team")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_team_challenges", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-updated_at", "-created_at"],
                "indexes": [
                    models.Index(fields=["status", "response_deadline"], name="team_chall_status_2ed5ac_idx"),
                    models.Index(fields=["challenger_team", "status"], name="team_chall_challeng_35c7f3_idx"),
                    models.Index(fields=["challenged_team", "status"], name="team_chall_challeng_a3021d_idx"),
                    models.Index(fields=["is_public", "status"], name="team_chall_is_publi_0c7e9d_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ChallengeProposal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", models.PositiveIntegerField()),
                ("court_mode", models.CharField(choices=[("PLAN_FIRST", "Plan first"), ("BOOKING_FIRST", "Confirmed booking")], max_length=20)),
                ("proposed_date", models.DateField(blank=True, null=True)),
                ("proposed_start_time", models.TimeField(blank=True, null=True)),
                ("proposed_end_time", models.TimeField(blank=True, null=True)),
                ("preferred_district", models.CharField(blank=True, max_length=50)),
                ("preferred_area", models.CharField(blank=True, max_length=100)),
                ("preferred_venue_name", models.CharField(blank=True, max_length=120)),
                ("players_per_side", models.PositiveSmallIntegerField(default=6)),
                ("intensity", models.CharField(default="CASUAL", max_length=20)),
                ("message", models.CharField(blank=True, max_length=500)),
                ("response_deadline", models.DateTimeField()),
                ("booking_deadline", models.DateTimeField(blank=True, null=True)),
                ("challenger_decision", models.CharField(choices=[("PENDING", "Pending"), ("ACCEPTED", "Accepted"), ("DECLINED", "Declined")], default="PENDING", max_length=12)),
                ("challenged_decision", models.CharField(choices=[("PENDING", "Pending"), ("ACCEPTED", "Accepted"), ("DECLINED", "Declined")], default="PENDING", max_length=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("booking", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="challenge_proposals", to="venues.booking")),
                ("challenge", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="proposals", to="team_challenges.teamchallenge")),
                ("created_by_team", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="challenge_proposals", to="teams.team")),
            ],
            options={
                "ordering": ["-version"],
            },
        ),
        migrations.AddField(
            model_name="teamchallenge",
            name="current_proposal",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="current_for_challenges", to="team_challenges.challengeproposal"),
        ),
        migrations.CreateModel(
            name="OpenChallengeResponse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("message", models.CharField(blank=True, max_length=500)),
                ("status", models.CharField(choices=[("PENDING", "Interested"), ("SELECTED", "Selected"), ("NOT_SELECTED", "Not selected"), ("WITHDRAWN", "Withdrawn")], default="PENDING", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("challenge", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="open_responses", to="team_challenges.teamchallenge")),
                ("responding_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="open_challenge_responses", to=settings.AUTH_USER_MODEL)),
                ("responding_team", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="open_challenge_responses", to="teams.team")),
            ],
            options={"ordering": ["created_at", "id"]},
        ),
        migrations.CreateModel(
            name="ChallengeEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_type", models.CharField(choices=[("CREATED", "Created"), ("RESPONSE_RECEIVED", "Response received"), ("OPPONENT_SELECTED", "Opponent selected"), ("COUNTERED", "Countered"), ("ACCEPTED", "Accepted"), ("DECLINED", "Declined"), ("WITHDRAWN", "Withdrawn"), ("EXPIRED", "Expired"), ("BOOKING_REQUIRED", "Booking required"), ("BOOKING_CONFIRMED", "Booking confirmed"), ("RECONFIRMATION_REQUIRED", "Reconfirmation required"), ("CANCELLED", "Cancelled")], max_length=32)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="team_challenge_events", to=settings.AUTH_USER_MODEL)),
                ("challenge", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="events", to="team_challenges.teamchallenge")),
                ("proposal", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="events", to="team_challenges.challengeproposal")),
                ("team", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="challenge_events", to="teams.team")),
            ],
            options={"ordering": ["created_at", "id"]},
        ),
        migrations.CreateModel(
            name="TeamFixture",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("AWAITING_COURT", "Court booking required"), ("SCHEDULED", "Scheduled"), ("IN_PROGRESS", "In progress"), ("COMPLETED", "Completed"), ("CANCELLED", "Cancelled"), ("RECONFIRMATION_REQUIRED", "Schedule change requested")], default="AWAITING_COURT", max_length=32)),
                ("result", models.CharField(blank=True, max_length=20)),
                ("result_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("booking", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="team_fixture", to="venues.booking")),
                ("challenge", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="fixture", to="team_challenges.teamchallenge")),
            ],
        ),
        migrations.AddConstraint(
            model_name="teamchallenge",
            constraint=models.UniqueConstraint(condition=Q(("team_pair_key__gt", ""), ("status__in", ("OPEN", "COUNTERED", "ACCEPTED_AWAITING_BOOKING", "RECONFIRMATION_REQUIRED", "CONFIRMED"))), fields=("team_pair_key",), name="unique_active_team_challenge_pair"),
        ),
        migrations.AddConstraint(
            model_name="teamchallenge",
            constraint=models.UniqueConstraint(condition=~Q(("client_request_id", "")), fields=("created_by", "client_request_id"), name="unique_team_challenge_create_request"),
        ),
        migrations.AddConstraint(
            model_name="challengeproposal",
            constraint=models.UniqueConstraint(fields=("challenge", "version"), name="unique_challenge_proposal_version"),
        ),
        migrations.AddConstraint(
            model_name="openchallengeresponse",
            constraint=models.UniqueConstraint(fields=("challenge", "responding_team"), name="unique_open_challenge_team_response"),
        ),
    ]
