# Generated by Django 5.2.16 on 2026-08-27 18:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_challenges', '0001_initial'),
        ('teams', '0004_team_accepts_team_challenges'),
        ('venues', '0015_booking_matchmaking_sync_error_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='teamchallenge',
            name='unique_active_team_challenge_pair',
        ),
        migrations.RenameIndex(
            model_name='teamchallenge',
            new_name='team_challe_status_4d716d_idx',
            old_name='team_chall_status_2ed5ac_idx',
        ),
        migrations.RenameIndex(
            model_name='teamchallenge',
            new_name='team_challe_challen_acd05b_idx',
            old_name='team_chall_challeng_35c7f3_idx',
        ),
        migrations.RenameIndex(
            model_name='teamchallenge',
            new_name='team_challe_challen_340953_idx',
            old_name='team_chall_challeng_a3021d_idx',
        ),
        migrations.RenameIndex(
            model_name='teamchallenge',
            new_name='team_challe_is_publ_239b31_idx',
            old_name='team_chall_is_publi_0c7e9d_idx',
        ),
        migrations.AddConstraint(
            model_name='teamchallenge',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('OPEN', 'COUNTERED', 'ACCEPTED_AWAITING_BOOKING', 'RECONFIRMATION_REQUIRED', 'CONFIRMED')), ('team_pair_key__gt', '')), fields=('team_pair_key',), name='unique_active_team_challenge_pair'),
        ),
    ]
