# Generated by Django 5.0.6 on 2026-08-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_challenges', '0002_remove_teamchallenge_unique_active_team_challenge_pair_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamchallenge',
            name='reconfirmation_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamchallenge',
            name='reconfirmation_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
