# Generated by Django 5.2.16 on 2026-08-30 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_challenges', '0004_teamfixture_result_confirmed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamFixtureChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=120)),
                ('body', models.TextField(max_length=1000)),
                ('client_message_id', models.CharField(blank=True, max_length=64)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='team_challenges.teamfixture')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_fixture_chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['fixture', '-created_at', '-id'], name='fixture_chat_history_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('client_message_id__gt', '')), fields=('fixture', 'sender', 'client_message_id'), name='unique_fixture_chat_client_message')],
            },
        ),
    ]
