# Generated by Django 5.2.16 on 2026-08-31 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_challenges', '0005_teamfixturechatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamfixtureparticipant',
            name='status',
            field=models.CharField(choices=[('SELECTED', 'Selected'), ('ATTENDED', 'Attended'), ('ABSENT', 'Absent'), ('UNVERIFIED', 'Attendance unverified'), ('WITHDRAWN', 'Withdrawn')], default='SELECTED', max_length=20),
        ),
    ]
