# Generated by Django 5.2.16 on 2026-08-31 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_challenges', '0006_alter_teamfixtureparticipant_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamchallenge',
            name='source',
            field=models.CharField(choices=[('TEAM_CHALLENGE', 'Team challenge'), ('INSTANT_SCORER', 'Instant scorer')], default='TEAM_CHALLENGE', max_length=24),
        ),
    ]
