# Generated by Django 5.0.6 on 2026-07-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('TEAM_INVITATION', 'Team Invitation'), ('INVITATION_ACCEPTED', 'Invitation Accepted'), ('INVITATION_REJECTED', 'Invitation Rejected'), ('TEAM_MEMBER_REMOVED', 'Team Member Removed'), ('VENUE_SUBMITTED', 'Venue Submitted'), ('VENUE_APPROVED', 'Venue Approved'), ('VENUE_NEEDS_CHANGES', 'Venue Needs Changes'), ('VENUE_REJECTED', 'Venue Rejected'), ('VENUE_SUSPENDED', 'Venue Suspended'), ('BOOKING_RESERVED', 'Booking Reserved'), ('BOOKING_CONFIRMED', 'Booking Confirmed'), ('BOOKING_PAYMENT_FAILED', 'Booking Payment Failed'), ('BOOKING_CANCELLED', 'Booking Cancelled')], max_length=40),
        ),
    ]
