# Generated by Django 5.0.6 on 2026-07-28 17:42

from django.conf import settings
from django.db import migrations, models


def migrate_existing_notification_state(apps, schema_editor):
    Notification = apps.get_model("notifications", "Notification")
    TeamMember = apps.get_model("teams", "TeamMember")

    type_map = {
        "TEAM_INVITATION": "TEAM_INVITATION_RECEIVED",
        "INVITATION_ACCEPTED": "TEAM_INVITATION_ACCEPTED",
        "INVITATION_REJECTED": "TEAM_INVITATION_REJECTED",
        "REFUND_REQUESTED": "REFUND_PENDING",
    }
    team_types = {
        "TEAM_INVITATION_RECEIVED",
        "TEAM_INVITATION_ACCEPTED",
        "TEAM_INVITATION_REJECTED",
        "TEAM_MEMBER_REMOVED",
    }
    booking_types = {
        "BOOKING_RESERVED",
        "BOOKING_CONFIRMED",
        "BOOKING_PAYMENT_FAILED",
        "BOOKING_CANCELLED",
        "REFUND_PENDING",
        "REFUND_UPDATED",
    }
    venue_types = {
        "VENUE_SUBMITTED",
        "VENUE_APPROVED",
        "VENUE_NEEDS_CHANGES",
        "VENUE_REJECTED",
        "VENUE_SUSPENDED",
    }

    for notification in Notification.objects.all().iterator():
        notification.notification_type = type_map.get(
            notification.notification_type,
            notification.notification_type,
        )
        if notification.notification_type in team_types:
            notification.category = "TEAMS"
        elif notification.notification_type in booking_types:
            notification.category = "BOOKINGS"
        elif notification.notification_type in venue_types:
            notification.category = "SYSTEM"

        if notification.is_read:
            notification.is_seen = True
            notification.seen_at = notification.created_at
            notification.read_at = notification.created_at

        metadata = notification.metadata or {}
        member_id = metadata.get("member_id")
        booking_id = metadata.get("booking_id")
        venue_id = metadata.get("venue_id")
        if member_id:
            notification.related_entity_type = "team_member"
            notification.related_entity_id = member_id
        elif booking_id:
            notification.related_entity_type = "booking"
            notification.related_entity_id = booking_id
        elif venue_id:
            notification.related_entity_type = "venue"
            notification.related_entity_id = venue_id

        if notification.notification_type == "TEAM_INVITATION_RECEIVED" and member_id:
            member = TeamMember.objects.filter(pk=member_id).first()
            if member and member.status == "INVITED":
                notification.action_required = True
                notification.action_status = "PENDING"
            elif member and member.status == "ACTIVE":
                notification.action_status = "ACCEPTED"
            elif member and member.status == "REJECTED":
                notification.action_status = "REJECTED"
            else:
                notification.action_status = "CANCELLED"

        notification.save()


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_notification_type'),
        ('teams', '0003_teammember_invited_at_teammember_member_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_status',
            field=models.CharField(choices=[('NONE', 'No Action'), ('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('COMPLETED', 'Completed')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('TEAMS', 'Teams'), ('CHALLENGES', 'Challenges'), ('MATCHES', 'Matches'), ('BOOKINGS', 'Bookings'), ('SYSTEM', 'System')], default='SYSTEM', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='deduplication_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('IMPORTANT', 'Important'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_entity_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_entity_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('TEAM_INVITATION_RECEIVED', 'Team Invitation Received'), ('TEAM_INVITATION_ACCEPTED', 'Team Invitation Accepted'), ('TEAM_INVITATION_REJECTED', 'Team Invitation Rejected'), ('TEAM_MEMBER_JOINED', 'Team Member Joined'), ('TEAM_MEMBER_REMOVED', 'Team Member Removed'), ('JOIN_REQUEST_RECEIVED', 'Join Request Received'), ('JOIN_REQUEST_ACCEPTED', 'Join Request Accepted'), ('JOIN_REQUEST_REJECTED', 'Join Request Rejected'), ('CHALLENGE_RECEIVED', 'Challenge Received'), ('CHALLENGE_ACCEPTED', 'Challenge Accepted'), ('CHALLENGE_REJECTED', 'Challenge Rejected'), ('CHALLENGE_COUNTERED', 'Challenge Countered'), ('CHALLENGE_EXPIRED', 'Challenge Expired'), ('MATCH_SCHEDULED', 'Match Scheduled'), ('MATCH_UPDATED', 'Match Updated'), ('MATCH_CANCELLED', 'Match Cancelled'), ('MATCH_REMINDER', 'Match Reminder'), ('GAME_ROOM_CREATED', 'Game Room Created'), ('GAME_ROOM_UPDATED', 'Game Room Updated'), ('RATING_REQUIRED', 'Rating Required'), ('VENUE_SUBMITTED', 'Venue Submitted'), ('VENUE_APPROVED', 'Venue Approved'), ('VENUE_NEEDS_CHANGES', 'Venue Needs Changes'), ('VENUE_REJECTED', 'Venue Rejected'), ('VENUE_SUSPENDED', 'Venue Suspended'), ('VENUE_MESSAGE', 'Venue Message'), ('BOOKING_RESERVED', 'Booking Reserved'), ('BOOKING_CONFIRMED', 'Booking Confirmed'), ('BOOKING_PAYMENT_FAILED', 'Booking Payment Failed'), ('BOOKING_CANCELLED_BY_PLAYER', 'Booking Cancelled By Player'), ('BOOKING_CANCELLED_BY_OWNER', 'Booking Cancelled By Owner'), ('BOOKING_REMINDER', 'Booking Reminder'), ('BOOKING_COMPLETED', 'Booking Completed'), ('REFUND_PENDING', 'Refund Pending'), ('REFUND_APPROVED', 'Refund Approved'), ('REFUND_REJECTED', 'Refund Rejected'), ('REFUND_COMPLETED', 'Refund Completed'), ('DISPUTE_CREATED', 'Dispute Created'), ('DISPUTE_UPDATED', 'Dispute Updated'), ('DISPUTE_RESOLVED', 'Dispute Resolved'), ('SYSTEM_ANNOUNCEMENT', 'System Announcement'), ('TEAM_INVITATION', 'Legacy Team Invitation'), ('INVITATION_ACCEPTED', 'Legacy Invitation Accepted'), ('INVITATION_REJECTED', 'Legacy Invitation Rejected'), ('BOOKING_CANCELLED', 'Legacy Booking Cancelled'), ('REFUND_REQUESTED', 'Legacy Refund Requested'), ('REFUND_UPDATED', 'Legacy Refund Updated')], max_length=40),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_seen', '-created_at'], name='notif_recipient_seen_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'category', '-created_at'], name='notif_recipient_cat_idx'),
        ),
        migrations.RunPython(migrate_existing_notification_state, migrations.RunPython.noop),
    ]
