# Generated by Django 5.0.6 on 2026-07-29 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notification_action_required_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('EMAIL_VERIFICATION_OTP', 'Email Verification OTP'), ('EMAIL_VERIFIED', 'Email Verified'), ('PASSWORD_RESET', 'Password Reset'), ('PASSWORD_CHANGED', 'Password Changed'), ('TEAM_INVITATION', 'Team Invitation'), ('BOOKING_CONFIRMED', 'Booking Confirmed'), ('BOOKING_PAYMENT_FAILED', 'Booking Payment Failed'), ('BOOKING_CANCELLED', 'Booking Cancelled'), ('BOOKING_REMINDER', 'Booking Reminder'), ('REFUND_PENDING', 'Refund Pending'), ('REFUND_COMPLETED', 'Refund Completed'), ('VENUE_SUBMITTED', 'Venue Submitted'), ('VENUE_REVIEWED', 'Venue Reviewed'), ('VENUE_MESSAGE', 'Venue Message')], max_length=40)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=180)),
                ('deduplication_key', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('related_entity_type', models.CharField(blank=True, max_length=50)),
                ('related_entity_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=300)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='email_recipient_created_idx'), models.Index(fields=['email_type', 'status'], name='email_type_status_idx')],
            },
        ),
    ]
