# Generated by Django 5.0.6 on 2026-07-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_emaildelivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaildelivery',
            name='email_type',
            field=models.CharField(choices=[('EMAIL_VERIFICATION_OTP', 'Email Verification OTP'), ('EMAIL_VERIFIED', 'Email Verified'), ('PASSWORD_RESET', 'Password Reset'), ('PASSWORD_CHANGED', 'Password Changed'), ('TEAM_INVITATION', 'Team Invitation'), ('BOOKING_CONFIRMED', 'Booking Confirmed'), ('BOOKING_PAYMENT_FAILED', 'Booking Payment Failed'), ('BOOKING_CANCELLED', 'Booking Cancelled'), ('BOOKING_REMINDER', 'Booking Reminder'), ('REFUND_PENDING', 'Refund Pending'), ('REFUND_COMPLETED', 'Refund Completed'), ('VENUE_SUBMITTED', 'Venue Submitted'), ('VENUE_STATUS', 'Venue Status'), ('VENUE_MESSAGE', 'Venue Message')], max_length=40),
        ),
    ]
