# Generated by Django 5.0.6 on 2026-07-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_alter_emaildelivery_email_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaildelivery',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('CONSOLE_PREVIEW', 'Console Preview'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
