# Generated by Django 5.2.16 on 2026-08-31 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('TEAM_INVITATION_RECEIVED', 'Team Invitation Received'), ('TEAM_INVITATION_ACCEPTED', 'Team Invitation Accepted'), ('TEAM_INVITATION_REJECTED', 'Team Invitation Rejected'), ('TEAM_MEMBER_JOINED', 'Team Member Joined'), ('TEAM_MEMBER_REMOVED', 'Team Member Removed'), ('JOIN_REQUEST_RECEIVED', 'Join Request Received'), ('JOIN_REQUEST_ACCEPTED', 'Join Request Accepted'), ('JOIN_REQUEST_REJECTED', 'Join Request Rejected'), ('CHALLENGE_RECEIVED', 'Challenge Received'), ('CHALLENGE_ACCEPTED', 'Challenge Accepted'), ('CHALLENGE_REJECTED', 'Challenge Rejected'), ('CHALLENGE_COUNTERED', 'Challenge Countered'), ('CHALLENGE_EXPIRED', 'Challenge Expired'), ('MATCH_SCHEDULED', 'Match Scheduled'), ('MATCH_UPDATED', 'Match Updated'), ('MATCH_CANCELLED', 'Match Cancelled'), ('MATCH_REMINDER', 'Match Reminder'), ('GAME_ROOM_CREATED', 'Game Room Created'), ('GAME_ROOM_UPDATED', 'Game Room Updated'), ('CHAT_MESSAGE_RECEIVED', 'Chat Message Received'), ('RATING_REQUIRED', 'Rating Required'), ('VENUE_SUBMITTED', 'Venue Submitted'), ('VENUE_APPROVED', 'Venue Approved'), ('VENUE_NEEDS_CHANGES', 'Venue Needs Changes'), ('VENUE_REJECTED', 'Venue Rejected'), ('VENUE_SUSPENDED', 'Venue Suspended'), ('VENUE_MESSAGE', 'Venue Message'), ('BOOKING_RESERVED', 'Booking Reserved'), ('BOOKING_CONFIRMED', 'Booking Confirmed'), ('BOOKING_PAYMENT_FAILED', 'Booking Payment Failed'), ('BOOKING_CANCELLED_BY_PLAYER', 'Booking Cancelled By Player'), ('BOOKING_CANCELLED_BY_OWNER', 'Booking Cancelled By Owner'), ('BOOKING_REMINDER', 'Booking Reminder'), ('BOOKING_COMPLETED', 'Booking Completed'), ('BOOKING_CHECKED_IN', 'Booking Checked In'), ('REFUND_PENDING', 'Refund Pending'), ('REFUND_APPROVED', 'Refund Approved'), ('REFUND_REJECTED', 'Refund Rejected'), ('REFUND_COMPLETED', 'Refund Completed'), ('DISPUTE_CREATED', 'Dispute Created'), ('DISPUTE_UPDATED', 'Dispute Updated'), ('DISPUTE_RESOLVED', 'Dispute Resolved'), ('SYSTEM_ANNOUNCEMENT', 'System Announcement'), ('TEAM_INVITATION', 'Legacy Team Invitation'), ('INVITATION_ACCEPTED', 'Legacy Invitation Accepted'), ('INVITATION_REJECTED', 'Legacy Invitation Rejected'), ('BOOKING_CANCELLED', 'Legacy Booking Cancelled'), ('REFUND_REQUESTED', 'Legacy Refund Requested'), ('REFUND_UPDATED', 'Legacy Refund Updated')], max_length=40),
        ),
    ]
