# Generated by Django 5.0.6 on 2026-08-05 17:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0003_teammember_invited_at_teammember_member_type_and_more'),
        ('venues', '0013_courtslot_block_note_courtslot_block_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('PICKUP', 'Pickup Game'), ('FILL_SQUAD', 'Fill My Squad')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('RECRUITING', 'Open'), ('FULL', 'Full'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='RECRUITING', max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, max_length=800)),
                ('host_notes', models.CharField(blank=True, max_length=500)),
                ('game_room_note', models.CharField(blank=True, max_length=500)),
                ('min_skill_level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('OPEN', 'Open to all')], default='OPEN', max_length=20)),
                ('total_capacity', models.PositiveSmallIntegerField(default=12)),
                ('waitlist_enabled', models.BooleanField(default=True)),
                ('recruitment_deadline', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matchmaking_games', to='venues.booking')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_games', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fill_squad_games', to='teams.team')),
            ],
            options={
                'ordering': ['booking__slot__date', 'booking__slot__start_time', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, max_length=100)),
                ('participant_type', models.CharField(choices=[('HOST', 'Host'), ('TEAM_MEMBER', 'Team Member'), ('TEMPORARY', 'Temporary Player'), ('GUEST', 'Guest')], max_length=20)),
                ('role', models.CharField(choices=[('BATSMAN', 'Batsman'), ('BOWLER', 'Bowler'), ('ALL_ROUNDER', 'All-rounder'), ('WICKETKEEPER', 'Wicketkeeper'), ('ANY', 'Any role')], default='ANY', max_length=20)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('LEFT', 'Left'), ('REMOVED', 'Removed')], default='CONFIRMED', max_length=20)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_game_participants', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='matchmaking.game')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GameRoleRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('BATSMAN', 'Batsman'), ('BOWLER', 'Bowler'), ('ALL_ROUNDER', 'All-rounder'), ('WICKETKEEPER', 'Wicketkeeper'), ('ANY', 'Any role')], max_length=20)),
                ('required_count', models.PositiveSmallIntegerField(default=1)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_requirements', to='matchmaking.game')),
            ],
            options={
                'ordering': ['role'],
            },
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_role', models.CharField(choices=[('BATSMAN', 'Batsman'), ('BOWLER', 'Bowler'), ('ALL_ROUNDER', 'All-rounder'), ('WICKETKEEPER', 'Wicketkeeper'), ('ANY', 'Any role')], default='ANY', max_length=20)),
                ('message', models.CharField(blank=True, max_length=400)),
                ('attendance_confirmed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WAITLISTED', 'Waitlisted'), ('WITHDRAWN', 'Withdrawn')], default='PENDING', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('waitlist_position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_game_join_requests', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='matchmaking.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['game_type', 'status'], name='matchmaking_game_ty_cdf8f0_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['host', 'status'], name='matchmaking_host_id_4bdd06_idx'),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['DRAFT', 'RECRUITING', 'FULL', 'IN_PROGRESS', 'COMPLETED'])), fields=('booking',), name='unique_active_matchmaking_game_per_booking'),
        ),
        migrations.AddConstraint(
            model_name='gameparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('game', 'user'), name='unique_registered_game_participant'),
        ),
        migrations.AddConstraint(
            model_name='gamerolerequirement',
            constraint=models.UniqueConstraint(fields=('game', 'role'), name='unique_game_role_requirement'),
        ),
        migrations.AddConstraint(
            model_name='joinrequest',
            constraint=models.UniqueConstraint(fields=('game', 'player'), name='unique_join_request_per_game_player'),
        ),
    ]
