# Generated by Django 5.2.16 on 2026-08-05 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0001_initial'),
        ('teams', '0003_teammember_invited_at_teammember_member_type_and_more'),
        ('venues', '0013_courtslot_block_note_courtslot_block_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['proposed_date', 'proposed_start_time', 'booking__slot__date', 'booking__slot__start_time', '-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='game',
            name='unique_active_matchmaking_game_per_booking',
        ),
        migrations.AddField(
            model_name='game',
            name='alternative_details',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='game',
            name='booking_attached_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='booking_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='creation_mode',
            field=models.CharField(choices=[('BOOKING_FIRST', 'Use Existing Booking'), ('PLAN_FIRST', 'Plan First')], default='BOOKING_FIRST', max_length=20),
        ),
        migrations.AddField(
            model_name='game',
            name='equipment_instructions',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='game',
            name='game_intensity',
            field=models.CharField(choices=[('CASUAL', 'Casual'), ('COMPETITIVE', 'Competitive'), ('PRACTICE', 'Practice / Friendly')], default='CASUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='game',
            name='minimum_players_to_proceed',
            field=models.PositiveSmallIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='game',
            name='preferred_area',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='preferred_venue_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='game',
            name='proposed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='proposed_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='proposed_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='reporting_instructions',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='game',
            name='requires_reconfirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matchmaking_games', to='venues.booking'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('PICKUP', 'Pickup Game'), ('FILL_SQUAD', 'Fill My Squad')], default='PICKUP', max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('RECRUITING', 'Open'), ('FULL', 'Full'), ('CLOSED', 'Recruitment Closed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='RECRUITING', max_length=20),
        ),
        migrations.AlterField(
            model_name='gameparticipant',
            name='participant_type',
            field=models.CharField(choices=[('HOST', 'Host'), ('TEAM_MEMBER', 'Team Member'), ('TEMPORARY', 'Player'), ('GUEST', 'Guest')], max_length=20),
        ),
        migrations.AlterField(
            model_name='gameparticipant',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('PROVISIONAL', 'Provisional'), ('RECONFIRM_REQUIRED', 'Reconfirmation Required'), ('DECLINED', 'Declined'), ('LEFT', 'Left'), ('REMOVED', 'Removed')], default='CONFIRMED', max_length=24),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['creation_mode', 'status'], name='matchmaking_creatio_5d188a_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['proposed_date', 'proposed_start_time'], name='matchmaking_propose_5d5551_idx'),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.UniqueConstraint(condition=models.Q(('booking__isnull', False), ('status__in', ['DRAFT', 'RECRUITING', 'FULL', 'CLOSED', 'IN_PROGRESS', 'COMPLETED'])), fields=('booking',), name='unique_active_matchmaking_game_per_booking'),
        ),
    ]
