# Generated by Codex on 2026-08-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matchmaking", "0003_alter_joinrequest_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joinrequest",
            name="status",
            field=models.CharField(choices=[("PENDING", "Pending"), ("ACCEPTED", "Accepted"), ("REJECTED", "Rejected"), ("WAITLISTED", "Waitlisted"), ("INVITED", "Invited"), ("WITHDRAWN", "Withdrawn"), ("EXPIRED", "Expired")], default="PENDING", max_length=20),
        ),
    ]
