# Generated by Django 5.2.16 on 2026-08-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0004_alter_joinrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='preferred_district',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
