# Generated by Django 5.2.16 on 2026-08-19 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0005_game_preferred_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WAITLISTED', 'Waitlisted'), ('INVITED', 'Invited'), ('WITHDRAWN', 'Withdrawn'), ('REMOVED', 'Removed by host'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20),
        ),
    ]
