# Generated by Django 5.2.16 on 2026-08-19 09:40

from django.db import migrations, models


def migrate_guest_reconfirmation(apps, schema_editor):
    Game = apps.get_model("matchmaking", "Game")
    GameParticipant = apps.get_model("matchmaking", "GameParticipant")
    GameParticipant.objects.filter(
        participant_type="GUEST",
        status="RECONFIRM_REQUIRED",
    ).update(status="GUEST_CONFIRMATION_REQUIRED")
    for game in Game.objects.filter(requires_reconfirmation=True).iterator():
        has_pending = GameParticipant.objects.filter(
            game_id=game.id,
            status__in=["RECONFIRM_REQUIRED", "GUEST_CONFIRMATION_REQUIRED"],
        ).exists()
        if not has_pending:
            Game.objects.filter(id=game.id).update(requires_reconfirmation=False)


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0006_alter_joinrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameparticipant',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('PROVISIONAL', 'Provisional'), ('RECONFIRM_REQUIRED', 'Reconfirmation Required'), ('GUEST_CONFIRMATION_REQUIRED', 'Host Confirmation Required'), ('DECLINED', 'Declined'), ('LEFT', 'Left'), ('REMOVED', 'Removed')], default='CONFIRMED', max_length=32),
        ),
        migrations.RunPython(
            migrate_guest_reconfirmation,
            migrations.RunPython.noop,
        ),
    ]
