# Generated by Django 5.2.16 on 2026-08-25 18:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0007_alter_gameparticipant_status'),
        ('teams', '0003_teammember_invited_at_teammember_member_type_and_more'),
        ('venues', '0015_booking_matchmaking_sync_error_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinRequestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('INVITED', 'Invited'), ('WAITLISTED', 'Waitlisted'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn'), ('EXPIRED', 'Expired'), ('REMOVED', 'Removed')], max_length=20)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('current_status', models.CharField(max_length=20)),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='game',
            name='unique_active_matchmaking_game_per_booking',
        ),
        migrations.AddField(
            model_name='game',
            name='booking_handoff_was_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='client_request_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='game',
            name='recruitment_closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='recruitment_closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_game_recruitment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='recruitment_closed_reason',
            field=models.CharField(blank=True, choices=[('HOST_CLOSED', 'Closed by Host'), ('DEADLINE_PASSED', 'Recruitment Deadline Passed'), ('BOOKING_PAYMENT_PENDING', 'Court Payment In Progress'), ('BOOKING_PAYMENT_EXPIRED', 'Court Payment Was Not Completed')], max_length=40),
        ),
        migrations.AddField(
            model_name='gameparticipant',
            name='schedule_acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameparticipant',
            name='schedule_acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_guest_game_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gameparticipant',
            name='status_changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='gameparticipant',
            name='status_changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_game_participant_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='attempt_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('RECRUITING', 'Open'), ('FULL', 'Full'), ('CLOSED', 'Recruitment Closed'), ('BOOKING_PENDING', 'Court Payment In Progress'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='RECRUITING', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.UniqueConstraint(condition=models.Q(('booking__isnull', False), ('status__in', ['DRAFT', 'RECRUITING', 'FULL', 'CLOSED', 'BOOKING_PENDING', 'IN_PROGRESS', 'COMPLETED'])), fields=('booking',), name='unique_active_matchmaking_game_per_booking'),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.UniqueConstraint(condition=models.Q(('client_request_id', ''), _negated=True), fields=('host', 'client_request_id'), name='unique_matchmaking_create_request_per_host'),
        ),
        migrations.AddField(
            model_name='joinrequestevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_game_request_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='joinrequestevent',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_request_events', to='matchmaking.game'),
        ),
        migrations.AddField(
            model_name='joinrequestevent',
            name='join_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='matchmaking.joinrequest'),
        ),
        migrations.AddField(
            model_name='joinrequestevent',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_request_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
