# Generated by Django 5.0.6 on 2026-08-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0008_joinrequestevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='reconfirmation_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='reconfirmation_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
