# Generated by Django 5.2

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("matchmaking", "0009_game_reconfirmation_deadline_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameChatMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sender_name", models.CharField(max_length=120)),
                ("body", models.TextField(max_length=1000)),
                ("client_message_id", models.CharField(blank=True, max_length=64)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("game", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="chat_messages", to="matchmaking.game")),
                ("sender", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="game_chat_messages", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="gamechatmessage",
            constraint=models.UniqueConstraint(
                condition=Q(("client_message_id__gt", "")),
                fields=("game", "sender", "client_message_id"),
                name="unique_game_chat_client_message",
            ),
        ),
        migrations.AddIndex(
            model_name="gamechatmessage",
            index=models.Index(fields=["game", "-created_at", "-id"], name="game_chat_history_idx"),
        ),
    ]
