# Generated by Django 5.2.16 on 2026-07-12 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sportspot_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('profile_photo', models.URLField(blank=True)),
                ('preferred_sport', models.CharField(choices=[('CRICKSAL', 'Cricksal'), ('FUTSAL', 'Futsal')], max_length=20)),
                ('skill_level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], max_length=20)),
                ('location', models.CharField(max_length=120)),
                ('weekly_availability', models.TextField(blank=True)),
                ('playing_style', models.TextField(blank=True)),
                ('preferred_cricksal_role', models.CharField(choices=[('BATSMAN', 'Batsman'), ('BOWLER', 'Bowler'), ('ALL_ROUNDER', 'All-rounder'), ('WICKETKEEPER', 'Wicketkeeper'), ('NONE', 'None')], default='NONE', max_length=20)),
                ('preferred_futsal_role', models.CharField(choices=[('GOALKEEPER', 'Goalkeeper'), ('DEFENDER', 'Defender'), ('WINGER', 'Winger'), ('STRIKER', 'Striker'), ('ANY', 'Any'), ('NONE', 'None')], default='NONE', max_length=20)),
                ('reliability_score', models.PositiveSmallIntegerField(default=100)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('no_show_count', models.PositiveIntegerField(default=0)),
                ('late_cancellation_count', models.PositiveIntegerField(default=0)),
                ('completed_matches_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
