# Generated by Django 5.0.6 on 2026-07-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_playerprofile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='preferred_sport',
            field=models.CharField(choices=[('CRICKSAL', 'Cricksal'), ('FUTSAL', 'Futsal')], default='CRICKSAL', max_length=20),
        ),
    ]
