# Generated by Codex on 2026-08-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0003_alter_playerprofile_preferred_sport"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerprofile",
            name="availability_days",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="availability_time_periods",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="bio",
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
