# Generated by Django 5.0.6 on 2026-08-02 04:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_playerprofile_availability_bio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReliabilityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('GAME_COMPLETED_ATTENDED', 'Game Completed - Attended'), ('GAME_LATE_CANCELLATION', 'Game Late Cancellation'), ('GAME_NO_SHOW', 'Game No-Show'), ('GAME_WITHDRAWAL_ON_TIME', 'Game Withdrawal On Time'), ('GAME_CANCELLED_BY_OTHER_PARTY', 'Game Cancelled By Other Party'), ('MANUAL_ADJUSTMENT', 'Manual Adjustment')], max_length=40)),
                ('impact', models.CharField(choices=[('POSITIVE', 'Positive'), ('NEGATIVE', 'Negative'), ('NO_IMPACT', 'No Impact'), ('NEUTRAL', 'Neutral')], default='NEUTRAL', max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('points_delta', models.SmallIntegerField(default=0)),
                ('related_entity_type', models.CharField(blank=True, max_length=60)),
                ('related_entity_id', models.PositiveIntegerField(blank=True, null=True)),
                ('dedupe_key', models.CharField(blank=True, max_length=160, null=True, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reliability_events', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reliability_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['player', '-occurred_at'], name='players_rel_player__e7eee5_idx'), models.Index(fields=['event_type', 'related_entity_type', 'related_entity_id'], name='players_rel_event_t_9a8eb5_idx')],
            },
        ),
    ]
