# Generated by Django 5.0.6 on 2026-08-02 04:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_reliabilityevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('feedback_tags', models.JSONField(blank=True, default=list)),
                ('comment', models.TextField(blank=True, max_length=500)),
                ('related_entity_type', models.CharField(max_length=60)),
                ('related_entity_id', models.PositiveIntegerField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rated_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to=settings.AUTH_USER_MODEL)),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['rated_player', '-created_at'], name='players_pla_rated_p_f71e7d_idx'), models.Index(fields=['related_entity_type', 'related_entity_id'], name='players_pla_related_8fdbb0_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='playerrating',
            constraint=models.UniqueConstraint(fields=('rater', 'rated_player', 'related_entity_type', 'related_entity_id'), name='unique_player_rating_per_context'),
        ),
    ]
