# Generated by Django 5.0.6 on 2026-08-02 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_playerrating_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerRatingEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('related_entity_type', models.CharField(max_length=60)),
                ('related_entity_id', models.PositiveIntegerField()),
                ('match_date', models.DateTimeField(blank=True, null=True)),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rated_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_requests_received', to=settings.AUTH_USER_MODEL)),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_eligibilities', to=settings.AUTH_USER_MODEL)),
                ('submitted_rating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eligibility_records', to='players.playerrating')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['rater', 'status', '-created_at'], name='players_pla_rater_i_fa2fb5_idx'), models.Index(fields=['related_entity_type', 'related_entity_id'], name='players_pla_related_8b5b50_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='playerratingeligibility',
            constraint=models.UniqueConstraint(fields=('rater', 'rated_player', 'related_entity_type', 'related_entity_id'), name='unique_rating_eligibility_per_context'),
        ),
    ]
