# Generated by Django 5.2.16 on 2026-08-29 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_playerratingeligibility_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipationCommitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('MATCHMAKING_GAME', 'Matchmaking game'), ('TEAM_FIXTURE', 'Team fixture')], max_length=30)),
                ('source_id', models.PositiveBigIntegerField()),
                ('source_participant_id', models.PositiveBigIntegerField()),
                ('source_version', models.PositiveSmallIntegerField(default=1)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('late_cutoff_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('COMMITTED', 'Committed'), ('CANCELLED_EARLY', 'Cancelled early'), ('LATE_CANCELLED', 'Cancelled late'), ('ATTENDANCE_PENDING', 'Attendance pending'), ('ATTENDED', 'Attended'), ('NO_SHOW_REPORTED', 'No-show reported'), ('FINALIZED_NO_SHOW', 'Finalized no-show'), ('DISPUTED', 'Disputed'), ('EXCUSED', 'Excused'), ('VOID', 'Voided')], default='COMMITTED', max_length=24)),
                ('attendance_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('review_deadline_at', models.DateTimeField(blank=True, null=True)),
                ('disputed_at', models.DateTimeField(blank=True, null=True)),
                ('dispute_reason', models.CharField(blank=True, max_length=500)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance_recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_participation_attendance', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation_commitments', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_participation_disputes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_at', '-id'],
                'indexes': [models.Index(fields=['source_type', 'source_id', 'status'], name='players_par_source__652408_idx'), models.Index(fields=['player', 'status', '-start_at'], name='players_par_player__e0df36_idx'), models.Index(fields=['status', 'review_deadline_at'], name='players_par_status_1c71fb_idx')],
                'constraints': [models.UniqueConstraint(fields=('player', 'source_type', 'source_id', 'source_version'), name='unique_participation_commitment_version')],
            },
        ),
    ]
