# Generated by Django 5.2.16 on 2026-08-31 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_participationcommitment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='participationcommitment',
            name='status',
            field=models.CharField(choices=[('COMMITTED', 'Committed'), ('CANCELLED_EARLY', 'Cancelled early'), ('LATE_CANCELLED', 'Cancelled late'), ('ATTENDANCE_PENDING', 'Attendance pending'), ('ATTENDED', 'Attended'), ('NO_SHOW_REPORTED', 'No-show reported'), ('FINALIZED_NO_SHOW', 'Finalized no-show'), ('DISPUTED', 'Disputed'), ('UNVERIFIED', 'Attendance unverified'), ('EXCUSED', 'Excused'), ('VOID', 'Voided')], default='COMMITTED', max_length=24),
        ),
        migrations.CreateModel(
            name='ParticipationAttendanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ATTENDANCE_RECORDED', 'Attendance recorded'), ('NO_SHOW_REPORTED', 'No-show reported'), ('ATTENDANCE_DISPUTED', 'Attendance disputed'), ('NO_SHOW_FINALIZED', 'No-show finalized'), ('ATTENDANCE_UNVERIFIED', 'Attendance left unverified'), ('DISPUTE_RESOLVED', 'Attendance dispute resolved'), ('COMMITMENT_CANCELLED', 'Commitment cancelled'), ('COMMITMENT_VOIDED', 'Commitment voided'), ('COMMITMENT_EXCUSED', 'Commitment excused')], max_length=32)),
                ('previous_status', models.CharField(blank=True, max_length=24)),
                ('current_status', models.CharField(max_length=24)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendance_events', to=settings.AUTH_USER_MODEL)),
                ('commitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_events', to='players.participationcommitment')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['commitment', 'created_at'], name='players_par_commitm_8416d4_idx'), models.Index(fields=['event_type', 'created_at'], name='players_par_event_t_a07dc0_idx')],
            },
        ),
    ]
