# Generated by Django 5.2.16 on 2026-08-31 17:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team_challenges', '0006_alter_teamfixtureparticipant_status'),
        ('teams', '0004_team_accepts_team_challenges'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CricketMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SETUP', 'Lineups and toss'), ('INNINGS_ONE', 'First innings'), ('INNINGS_BREAK', 'Innings break'), ('INNINGS_TWO', 'Second innings'), ('COMPLETED', 'Completed')], default='SETUP', max_length=20)),
                ('overs_per_innings', models.PositiveSmallIntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('toss_decision', models.CharField(blank=True, choices=[('BAT', 'Bat'), ('BOWL', 'Bowl')], max_length=8)),
                ('challenger_squad_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('challenged_squad_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=200)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenged_squad_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_challenged_cricket_squads', to=settings.AUTH_USER_MODEL)),
                ('challenger_squad_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_challenger_cricket_squads', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_cricket_matches', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_cricket_matches', to=settings.AUTH_USER_MODEL)),
                ('first_batting_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='first_batting_cricket_matches', to='teams.team')),
                ('fixture', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cricket_match', to='team_challenges.teamfixture')),
                ('scorer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cricket_matches', to=settings.AUTH_USER_MODEL)),
                ('second_batting_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='second_batting_cricket_matches', to='teams.team')),
                ('toss_winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='won_cricket_tosses', to='teams.team')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CricketSquadPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=120)),
                ('batting_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fixture_participant', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cricket_squad_entry', to='team_challenges.teamfixtureparticipant')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squad_players', to='scoring.cricketmatch')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cricket_squad_appearances', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cricket_squad_players', to='teams.team')),
            ],
            options={
                'ordering': ['team_id', 'batting_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CricketInnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
                ('target_runs', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=20)),
                ('closing_reason', models.CharField(blank=True, choices=[('ALL_OUT', 'All out'), ('OVERS_COMPLETE', 'Overs complete'), ('TARGET_REACHED', 'Target reached')], max_length=20)),
                ('total_runs', models.PositiveSmallIntegerField(default=0)),
                ('wickets', models.PositiveSmallIntegerField(default=0)),
                ('legal_balls', models.PositiveSmallIntegerField(default=0)),
                ('wide_runs', models.PositiveSmallIntegerField(default=0)),
                ('no_ball_runs', models.PositiveSmallIntegerField(default=0)),
                ('bye_runs', models.PositiveSmallIntegerField(default=0)),
                ('leg_bye_runs', models.PositiveSmallIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batting_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cricket_batting_innings', to='teams.team')),
                ('bowling_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cricket_bowling_innings', to='teams.team')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innings', to='scoring.cricketmatch')),
                ('current_bowler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='currently_bowling', to='scoring.cricketsquadplayer')),
                ('current_non_striker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='currently_non_striking', to='scoring.cricketsquadplayer')),
                ('current_striker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='currently_striking', to='scoring.cricketsquadplayer')),
                ('opening_bowler', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_bowling', to='scoring.cricketsquadplayer')),
                ('opening_non_striker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_as_non_striker', to='scoring.cricketsquadplayer')),
                ('opening_striker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_as_striker', to='scoring.cricketsquadplayer')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='CricketDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('runs_off_bat', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(6)])),
                ('extra_type', models.CharField(choices=[('NONE', 'No extra'), ('WIDE', 'Wide'), ('NO_BALL', 'No ball'), ('BYE', 'Bye'), ('LEG_BYE', 'Leg bye')], default='NONE', max_length=12)),
                ('extra_runs', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(7)])),
                ('wicket_kind', models.CharField(choices=[('NONE', 'No wicket'), ('BOWLED', 'Bowled'), ('CAUGHT', 'Caught'), ('LBW', 'LBW'), ('RUN_OUT', 'Run out'), ('STUMPED', 'Stumped'), ('HIT_WICKET', 'Hit wicket')], default='NONE', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_cricket_deliveries', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='scoring.cricketdelivery')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_cricket_deliveries', to=settings.AUTH_USER_MODEL)),
                ('innings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='scoring.cricketinnings')),
                ('bowler', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bowled_cricket_deliveries', to='scoring.cricketsquadplayer')),
                ('dismissed_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cricket_dismissals', to='scoring.cricketsquadplayer')),
                ('fielder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cricket_fielding_events', to='scoring.cricketsquadplayer')),
                ('incoming_batsman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entered_cricket_innings', to='scoring.cricketsquadplayer')),
                ('non_striker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='non_striker_cricket_deliveries', to='scoring.cricketsquadplayer')),
                ('striker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faced_cricket_deliveries', to='scoring.cricketsquadplayer')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='cricketsquadplayer',
            constraint=models.UniqueConstraint(fields=('match', 'player'), name='unique_cricket_match_squad_player'),
        ),
        migrations.AddConstraint(
            model_name='cricketsquadplayer',
            constraint=models.UniqueConstraint(fields=('match', 'team', 'batting_order'), name='unique_cricket_team_batting_order'),
        ),
        migrations.AddConstraint(
            model_name='cricketinnings',
            constraint=models.UniqueConstraint(fields=('match', 'number'), name='unique_cricket_match_innings_number'),
        ),
        migrations.AddIndex(
            model_name='cricketdelivery',
            index=models.Index(fields=['innings', 'is_active', 'sequence'], name='scoring_cri_innings_66930d_idx'),
        ),
        migrations.AddConstraint(
            model_name='cricketdelivery',
            constraint=models.UniqueConstraint(fields=('innings', 'sequence'), name='unique_cricket_innings_delivery_sequence'),
        ),
    ]
