# Generated by Django 5.2.16 on 2026-08-31 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
        ('team_challenges', '0007_teamchallenge_source'),
        ('teams', '0004_team_accepts_team_challenges'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CricketPlayerPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs', models.PositiveSmallIntegerField(default=0)),
                ('balls_faced', models.PositiveSmallIntegerField(default=0)),
                ('fours', models.PositiveSmallIntegerField(default=0)),
                ('sixes', models.PositiveSmallIntegerField(default=0)),
                ('balls_bowled', models.PositiveSmallIntegerField(default=0)),
                ('runs_conceded', models.PositiveSmallIntegerField(default=0)),
                ('wickets', models.PositiveSmallIntegerField(default=0)),
                ('wides', models.PositiveSmallIntegerField(default=0)),
                ('no_balls', models.PositiveSmallIntegerField(default=0)),
                ('catches', models.PositiveSmallIntegerField(default=0)),
                ('run_outs', models.PositiveSmallIntegerField(default=0)),
                ('stumpings', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_performances', to='scoring.cricketmatch')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cricket_performances', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cricket_player_performances', to='teams.team')),
            ],
            options={
                'ordering': ['-match__completed_at', '-id'],
                'indexes': [models.Index(fields=['player', '-updated_at'], name='scoring_cri_player__8248b2_idx'), models.Index(fields=['team', '-updated_at'], name='scoring_cri_team_id_f12814_idx')],
                'constraints': [models.UniqueConstraint(fields=('match', 'player'), name='unique_cricket_performance_per_match')],
            },
        ),
        migrations.CreateModel(
            name='ScoringMatchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=16)),
                ('client_request_id', models.CharField(blank=True, max_length=64)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenged_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_scoring_match_requests', to='teams.team')),
                ('challenger_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_scoring_match_requests', to='teams.team')),
                ('fixture', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instant_scoring_request', to='team_challenges.teamfixture')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_scoring_matches', to=settings.AUTH_USER_MODEL)),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_scoring_match_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['challenged_team', 'status', '-created_at'], name='scoring_sco_challen_a989da_idx'), models.Index(fields=['challenger_team', 'status', '-created_at'], name='scoring_sco_challen_89fb77_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('challenger_team', 'challenged_team'), name='unique_pending_scoring_request_direction'), models.UniqueConstraint(condition=models.Q(('client_request_id__gt', '')), fields=('requested_by', 'client_request_id'), name='unique_scoring_request_client_id')],
            },
        ),
    ]
