# Generated by Django 5.0.6 on 2026-07-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='verification_document_type',
            field=models.CharField(blank=True, choices=[('BUSINESS_REGISTRATION', 'Business Registration Document'), ('PAN_VAT', 'PAN/VAT Document'), ('RENTAL_LEASE', 'Rental/Lease Agreement'), ('UTILITY_BILL', 'Utility Bill'), ('PERMISSION_LETTER', 'Permission Letter')], max_length=30),
        ),
    ]
