# Generated by Django 5.0.6 on 2026-07-14 08:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_venue_verification_document_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenuePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('OUTSIDE', 'Outside / Front'), ('COURT_AREA', 'Court / Play Area'), ('ADDITIONAL', 'Additional')], max_length=20)),
                ('image', models.FileField(upload_to='venues/gallery/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='venues.venue')),
            ],
            options={
                'ordering': ['category', '-uploaded_at'],
            },
        ),
    ]
