# Generated by Django 5.0.6 on 2026-07-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_venuephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='cancellation_policy',
            field=models.TextField(blank=True),
        ),
    ]
