# Generated by Django 5.0.6 on 2026-07-15 11:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_venue_cancellation_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_items', to='venues.booking')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_items', to='venues.courtslot')),
            ],
            options={
                'ordering': ['slot__date', 'slot__start_time', 'slot__end_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='bookingslot',
            constraint=models.UniqueConstraint(fields=('booking', 'slot'), name='unique_booking_slot'),
        ),
    ]
