# Generated by Codex on 2026-07-18

from django.db import migrations, models


def move_refunds_to_owner_action(apps, schema_editor):
    Booking = apps.get_model("venues", "Booking")
    Booking.objects.filter(refund_status="PENDING_ADMIN_APPROVAL").update(refund_status="PENDING_OWNER_ACTION")
    Booking.objects.filter(refund_status="APPROVED").update(refund_status="PENDING_OWNER_ACTION")


def move_refunds_back_to_admin_action(apps, schema_editor):
    Booking = apps.get_model("venues", "Booking")
    Booking.objects.filter(refund_status="PENDING_OWNER_ACTION").update(refund_status="PENDING_ADMIN_APPROVAL")


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0007_booking_refund_admin_note_booking_refund_reason_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="refund_admin_note",
            new_name="refund_owner_note",
        ),
        migrations.RunPython(move_refunds_to_owner_action, move_refunds_back_to_admin_action),
        migrations.AlterField(
            model_name="booking",
            name="refund_status",
            field=models.CharField(
                choices=[
                    ("NOT_REQUIRED", "Not Required"),
                    ("PENDING_OWNER_ACTION", "Pending Owner Action"),
                    ("NOT_ELIGIBLE", "Not Eligible"),
                    ("REJECTED", "Rejected"),
                    ("REFUNDED", "Refunded"),
                ],
                default="NOT_REQUIRED",
                max_length=30,
            ),
        ),
    ]
