# Generated by Django 5.0.6 on 2026-07-28 18:28

import django.core.validators
from django.db import migrations, models


def backfill_policy_snapshots(apps, schema_editor):
    Booking = apps.get_model("venues", "Booking")

    for booking in Booking.objects.select_related("venue").iterator():
        venue = booking.venue
        booking.cancellation_policy_snapshot = {
            "version": venue.cancellation_policy_version,
            "full_refund_hours": venue.cancellation_full_refund_hours,
            "partial_refund_enabled": venue.cancellation_partial_refund_enabled,
            "partial_refund_hours": venue.cancellation_partial_refund_hours,
            "partial_refund_percent": venue.cancellation_partial_refund_percent,
            "additional_notes": venue.cancellation_policy,
            "captured_at": booking.created_at.isoformat(),
        }

        if booking.refund_status in ["REFUNDED", "PENDING_OWNER_ACTION"]:
            booking.cancellation_tier = "FULL_REFUND"
            booking.refund_percentage = 100
            booking.refund_amount = booking.amount
        elif booking.refund_status == "NOT_ELIGIBLE" or booking.payment_status == "NO_REFUND":
            booking.cancellation_tier = "NO_REFUND"
            booking.refund_percentage = 0
            booking.refund_amount = 0

        booking.save(
            update_fields=[
                "cancellation_policy_snapshot",
                "cancellation_tier",
                "refund_percentage",
                "refund_amount",
            ]
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0009_bookingmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_policy_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_tier',
            field=models.CharField(choices=[('NOT_APPLICABLE', 'Not Applicable'), ('UNPAID_RELEASE', 'Unpaid Reservation Released'), ('FULL_REFUND', 'Full Refund'), ('PARTIAL_REFUND', 'Partial Refund'), ('NO_REFUND', 'No Refund'), ('OWNER_FULL_REFUND', 'Owner Full Refund'), ('ADMIN_DECISION', 'Admin Decision')], default='NOT_APPLICABLE', max_length=30),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_percentage',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='venue',
            name='cancellation_full_refund_hours',
            field=models.PositiveSmallIntegerField(default=24, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(168)]),
        ),
        migrations.AddField(
            model_name='venue',
            name='cancellation_partial_refund_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='cancellation_partial_refund_hours',
            field=models.PositiveSmallIntegerField(default=12, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(167)]),
        ),
        migrations.AddField(
            model_name='venue',
            name='cancellation_partial_refund_percent',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='venue',
            name='cancellation_policy_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed'), ('REFUND_PENDING', 'Refund Pending'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially Refunded'), ('NO_REFUND', 'No Refund')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='refund_status',
            field=models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('PENDING_OWNER_ACTION', 'Pending Owner Action'), ('NOT_ELIGIBLE', 'Not Eligible'), ('REJECTED', 'Rejected'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially Refunded')], default='NOT_REQUIRED', max_length=30),
        ),
        migrations.AlterField(
            model_name='venue',
            name='cancellation_policy',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.RunPython(backfill_policy_snapshots, noop_reverse),
    ]
