# Generated by Django 5.0.6 on 2026-07-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0011_booking_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='khalti_payment_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='booking',
            name='khalti_pidx',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='booking',
            name='khalti_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='booking',
            name='khalti_status',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='booking',
            name='khalti_transaction_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_provider',
            field=models.CharField(choices=[('MOCK', 'Mock'), ('KHALTI', 'Khalti')], default='MOCK', max_length=20),
        ),
    ]
