# Generated by Django 5.0.6 on 2026-08-02 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0012_booking_khalti_payment_url_booking_khalti_pidx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courtslot',
            name='block_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='courtslot',
            name='block_reason',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='courtslot',
            name='block_type',
            field=models.CharField(blank=True, choices=[('MAINTENANCE', 'Maintenance'), ('TEMPORARY_CLOSURE', 'Temporary closure'), ('PRIVATE_USE', 'Private use'), ('VENUE_UNAVAILABLE', 'Venue unavailable'), ('OTHER', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='courtslot',
            name='blocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courtslot',
            name='blocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_court_slots', to=settings.AUTH_USER_MODEL),
        ),
    ]
