# Generated by Django 5.2.16 on 2026-08-06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("matchmaking", "0004_alter_joinrequest_status"),
        ("venues", "0013_courtslot_block_note_courtslot_block_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="matchmaking_game",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="booking_handoffs", to="matchmaking.game"),
        ),
    ]
