# Generated by Django 5.2.16 on 2026-08-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0014_booking_matchmaking_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='matchmaking_sync_error',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='booking',
            name='matchmaking_sync_status',
            field=models.CharField(choices=[('NOT_APPLICABLE', 'Not Applicable'), ('PENDING_PAYMENT', 'Waiting for Payment'), ('ATTACHED', 'Attached to Game'), ('RELEASED', 'Payment Was Not Completed'), ('RECONCILIATION_REQUIRED', 'Needs Review')], default='NOT_APPLICABLE', max_length=30),
        ),
    ]
