# Generated by Django 5.2.16 on 2026-08-28 06:53

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0015_booking_matchmaking_sync_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))]),
        ),
        migrations.AddField(
            model_name='venue',
            name='location_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='location_source',
            field=models.CharField(blank=True, choices=[('MANUAL_PIN', 'Confirmed map pin'), ('GEOCODED', 'Address search'), ('LEGACY_LINK', 'Legacy map link')], max_length=20),
        ),
        migrations.AddField(
            model_name='venue',
            name='location_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))]),
        ),
    ]
