# Generated by Django 5.2.16 on 2026-08-29 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0018_courtreviewcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtFeedbackReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('LIKE', 'Like'), ('DISLIKE', 'Dislike')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_reactions', to='venues.courtreviewcomment')),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_reactions', to='venues.courtreview')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='court_feedback_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('comment__isnull', True), ('review__isnull', False)), models.Q(('comment__isnull', False), ('review__isnull', True)), _connector='OR'), name='feedback_reaction_one_target'), models.UniqueConstraint(condition=models.Q(('review__isnull', False)), fields=('reviewer', 'review'), name='unique_feedback_reaction_per_review'), models.UniqueConstraint(condition=models.Q(('comment__isnull', False)), fields=('reviewer', 'comment'), name='unique_feedback_reaction_per_comment')],
            },
        ),
        migrations.CreateModel(
            name='CourtFeedbackReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('SPAM', 'Spam'), ('INAPPROPRIATE', 'Inappropriate content'), ('MISLEADING', 'Misleading information'), ('OTHER', 'Other')], max_length=20)),
                ('details', models.TextField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('REVIEWED', 'Reviewed'), ('DISMISSED', 'Dismissed')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_reports', to='venues.courtreviewcomment')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='court_feedback_reports', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_reports', to='venues.courtreview')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('comment__isnull', True), ('review__isnull', False)), models.Q(('comment__isnull', False), ('review__isnull', True)), _connector='OR'), name='feedback_report_one_target'), models.UniqueConstraint(condition=models.Q(('review__isnull', False)), fields=('reporter', 'review'), name='unique_feedback_report_per_review'), models.UniqueConstraint(condition=models.Q(('comment__isnull', False)), fields=('reporter', 'comment'), name='unique_feedback_report_per_comment')],
            },
        ),
    ]
