# Generated by Django 5.2.16 on 2026-08-29 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0019_courtfeedbackreaction_courtfeedbackreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CHECKED_IN', 'Checked in')], default='CHECKED_IN', max_length=20)),
                ('checked_in_at', models.DateTimeField()),
                ('scan_count', models.PositiveIntegerField(default=1)),
                ('last_scanned_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='check_in', to='venues.booking')),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_check_ins_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-checked_in_at'],
            },
        ),
    ]
