# Generated by Django 5.2.16 on 2026-08-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0020_bookingcheckin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='location_source',
            field=models.CharField(blank=True, choices=[('MANUAL_PIN', 'Confirmed map pin'), ('GEOCODED', 'Address search'), ('DEVICE_LOCATION', 'Device location'), ('LEGACY_LINK', 'Legacy map link')], max_length=20),
        ),
    ]
