from django.urls import path

from .views import (
    AdminVenueListView,
    AdminVenueReviewView,
    BookingCancelView,
    BookingDetailView,
    BookingReserveView,
    DiscoveryReferenceDataView,
    GenerateSlotsView,
    KhaltiPaymentInitiateView,
    KhaltiPaymentVerifyView,
    OwnerBookingMessageView,
    OwnerBookingsView,
    OwnerCourtDeactivateView,
    OwnerCourtDetailView,
    OwnerCourtListCreateView,
    OwnerSlotListView,
    OwnerVenueDeactivateView,
    OwnerVenueSubmitView,
    OwnerVenuePhotoDeleteView,
    OwnerVenuePhotoListCreateView,
    OwnerVenueView,
    OwnerRefundListView,
    OwnerRefundReviewView,
    PlayerBookingsView,
    PublicCourtDetailView,
    PublicCourtListView,
    PublicCourtSlotsView,
    PublicVenueDetailView,
    PublicVenueListView,
    SlotStatusView,
)

urlpatterns = [
    path("owner/venue/", OwnerVenueView.as_view(), name="owner-venue"),
    path("owner/venue/deactivate/", OwnerVenueDeactivateView.as_view(), name="owner-venue-deactivate"),
    path("owner/venue/submit/", OwnerVenueSubmitView.as_view(), name="owner-venue-submit"),
    path("owner/venue/photos/", OwnerVenuePhotoListCreateView.as_view(), name="owner-venue-photos"),
    path("owner/venue/photos/<int:photo_id>/", OwnerVenuePhotoDeleteView.as_view(), name="owner-venue-photo-delete"),
    path("owner/courts/", OwnerCourtListCreateView.as_view(), name="owner-courts"),
    path("owner/courts/<int:court_id>/", OwnerCourtDetailView.as_view(), name="owner-court-detail"),
    path("owner/courts/<int:court_id>/deactivate/", OwnerCourtDeactivateView.as_view(), name="owner-court-deactivate"),
    path("owner/courts/<int:court_id>/slots/generate/", GenerateSlotsView.as_view(), name="owner-generate-slots"),
    path("owner/slots/", OwnerSlotListView.as_view(), name="owner-slots"),
    path("owner/slots/<int:slot_id>/<str:action>/", SlotStatusView.as_view(), name="owner-slot-status"),
    path("owner/bookings/", OwnerBookingsView.as_view(), name="owner-bookings"),
    path("owner/bookings/<int:booking_id>/messages/", OwnerBookingMessageView.as_view(), name="owner-booking-message"),
    path("owner/refunds/", OwnerRefundListView.as_view(), name="owner-refunds"),
    path("owner/refunds/<int:booking_id>/review/", OwnerRefundReviewView.as_view(), name="owner-refund-review"),
    path("admin/venues/", AdminVenueListView.as_view(), name="admin-venues"),
    path("admin/venues/<int:venue_id>/review/", AdminVenueReviewView.as_view(), name="admin-venue-review"),
    path("discovery/reference/", DiscoveryReferenceDataView.as_view(), name="discovery-reference"),
    path("venues/", PublicVenueListView.as_view(), name="public-venues"),
    path("venues/<int:venue_id>/", PublicVenueDetailView.as_view(), name="public-venue-detail"),
    path("courts/", PublicCourtListView.as_view(), name="public-courts"),
    path("courts/<int:court_id>/", PublicCourtDetailView.as_view(), name="public-court-detail"),
    path("courts/<int:court_id>/slots/", PublicCourtSlotsView.as_view(), name="public-court-slots"),
    path("bookings/reserve/", BookingReserveView.as_view(), name="booking-reserve"),
    path("bookings/my/", PlayerBookingsView.as_view(), name="player-bookings"),
    path("bookings/<int:booking_id>/", BookingDetailView.as_view(), name="booking-detail"),
    path("bookings/<int:booking_id>/cancel/", BookingCancelView.as_view(), name="booking-cancel"),
    path("bookings/<int:booking_id>/khalti/initiate/", KhaltiPaymentInitiateView.as_view(), name="khalti-payment-initiate"),
    path("bookings/<int:booking_id>/khalti/verify/", KhaltiPaymentVerifyView.as_view(), name="khalti-payment-verify"),
]

