# Generated by Django 5.0.6 on 2026-07-13 09:28

from django.db import migrations, models


def mark_existing_guests(apps, schema_editor):
    TeamMember = apps.get_model("teams", "TeamMember")
    TeamMember.objects.filter(user__isnull=True).update(member_type="GUEST", role_in_team="GUEST")


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_team_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='invited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='member_type',
            field=models.CharField(choices=[('REGISTERED', 'Registered'), ('GUEST', 'Guest')], default='REGISTERED', max_length=20),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INVITED', 'Invited'), ('REJECTED', 'Rejected'), ('LEFT', 'Left'), ('REMOVED', 'Removed')], default='ACTIVE', max_length=20),
        ),
        migrations.RunPython(mark_existing_guests, migrations.RunPython.noop),
    ]
