# Generated by Django 5.2.16 on 2026-08-27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0003_teammember_invited_at_teammember_member_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="accepts_team_challenges",
            field=models.BooleanField(default=True),
        ),
    ]
