from django.urls import path

from .views import (
    ChallengeBookingAttachView,
    ChallengeCancelView,
    ChallengeCounterView,
    ChallengeDecisionView,
    ChallengeReconfirmationView,
    ChallengeRescheduleView,
    ChallengeWithdrawView,
    OpenChallengeResponseView,
    OpenChallengeResponseWithdrawView,
    OpenOpponentSelectionView,
    PublicChallengeTeamDetailView,
    PublicChallengeTeamListView,
    PublicOpenChallengeListView,
    TeamChallengeDetailView,
    TeamChallengeListCreateView,
    FixtureAttendanceView,
    FixtureParticipantCreateView,
    FixtureParticipantRemoveView,
    FixtureResultConfirmView,
    FixtureResultView,
    ChallengeFixtureRoomView,
    ChallengeReferenceDataView,
    FixtureEligiblePlayersView,
)


urlpatterns = [
    path("reference/", ChallengeReferenceDataView.as_view(), name="team-challenge-reference"),
    path("teams/", PublicChallengeTeamListView.as_view(), name="challenge-team-list"),
    path("teams/<int:team_id>/", PublicChallengeTeamDetailView.as_view(), name="challenge-team-detail"),
    path("challenges/", TeamChallengeListCreateView.as_view(), name="team-challenge-list-create"),
    path("challenges/public/", PublicOpenChallengeListView.as_view(), name="public-open-challenge-list"),
    path("challenges/<int:challenge_id>/", TeamChallengeDetailView.as_view(), name="team-challenge-detail"),
    path("challenges/<int:challenge_id>/decision/", ChallengeDecisionView.as_view(), name="team-challenge-decision"),
    path("challenges/<int:challenge_id>/counter/", ChallengeCounterView.as_view(), name="team-challenge-counter"),
    path("challenges/<int:challenge_id>/reconfirm/", ChallengeReconfirmationView.as_view(), name="team-challenge-reconfirm"),
    path("challenges/<int:challenge_id>/reschedule/", ChallengeRescheduleView.as_view(), name="team-challenge-reschedule"),
    path("challenges/<int:challenge_id>/open-response/", OpenChallengeResponseView.as_view(), name="team-challenge-open-response"),
    path("challenges/<int:challenge_id>/open-response/withdraw/", OpenChallengeResponseWithdrawView.as_view(), name="team-challenge-open-response-withdraw"),
    path("challenges/<int:challenge_id>/select-opponent/", OpenOpponentSelectionView.as_view(), name="team-challenge-select-opponent"),
    path("challenges/<int:challenge_id>/withdraw/", ChallengeWithdrawView.as_view(), name="team-challenge-withdraw"),
    path("challenges/<int:challenge_id>/attach-booking/", ChallengeBookingAttachView.as_view(), name="team-challenge-attach-booking"),
    path("challenges/<int:challenge_id>/cancel/", ChallengeCancelView.as_view(), name="team-challenge-cancel"),
    path("challenges/<int:challenge_id>/room/", ChallengeFixtureRoomView.as_view(), name="team-challenge-room"),
    path("fixtures/<int:fixture_id>/eligible-players/", FixtureEligiblePlayersView.as_view(), name="team-fixture-eligible-players"),
    path("fixtures/<int:fixture_id>/participants/", FixtureParticipantCreateView.as_view(), name="team-fixture-participant-create"),
    path("fixtures/<int:fixture_id>/participants/<int:participant_id>/remove/", FixtureParticipantRemoveView.as_view(), name="team-fixture-participant-remove"),
    path("fixtures/<int:fixture_id>/participants/<int:participant_id>/attendance/", FixtureAttendanceView.as_view(), name="team-fixture-participant-attendance"),
    path("fixtures/<int:fixture_id>/result/", FixtureResultView.as_view(), name="team-fixture-result"),
    path("fixtures/<int:fixture_id>/result/confirm/", FixtureResultConfirmView.as_view(), name="team-fixture-result-confirm"),
]
